name: CI Pipeline .NET + Angular

on:
  push:
    branches:
      - master
      - "feature/*"
      - "rama-*"
  pull_request:
    branches: [ master ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependencias backend
        run: dotnet restore ./backend

      - name: Compilar backend
        run: dotnet build ./backend --configuration Release --no-restore

      - name: Testear backend
        run: dotnet test ./backend --no-restore --verbosity normal

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependencias Angular
        run: cd frontend && npm install

      - name: Compilar Angular
        run: cd frontend && npm run build --if-present

      - name: Test Angular
        run: cd frontend && npm test -- --watch=false --no-progress --browsers=ChromeHeadless || echo "Sin tests"
